package com.test.SecondarySort.Example2;

import org.apache.hadoop.io.DoubleWritable;
import org.apache.hadoop.io.LongWritable;
import org.apache.hadoop.io.Text;
import org.apache.hadoop.mapreduce.Mapper;

import java.io.IOException;

public class SecondarySortMapper extends Mapper<LongWritable, Text, DateTemperaturePair, DoubleWritable>{
	   /**
	   * @param key is generated by Hadoop (ignored here)
	   * @param value has this format: "YYYY,MM,DD,temperature"
	   */
	private String yearMonth = new String();
    private String day = new String();
    private double temperature = 0.0;
	
	public void map(LongWritable key, Text value, Context context)
			throws IOException, InterruptedException {
			
		if (value.toString().length() > 0) {
			String line = value.toString().trim();
			String item[] = line.split(",");	
			yearMonth = item[0].trim()+"-"+item[1].trim();
			day = item[2];
			temperature = Double.parseDouble(item[3]);
			//System.out.println(" ** yearMonth ** "+yearMonth+" day "+day+" temperature "+temperature);
			context.write(
					new DateTemperaturePair(
							new Text(yearMonth),
							new DoubleWritable(temperature)), new DoubleWritable(temperature));
		}	
	 }
}
